version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_USER=${APP_USER:-developer}
        - APP_USER_PASSWORD=${APP_USER_PASSWORD:-developer123}
    container_name: da_monitor
    volumes:
      - .:/workspace
    depends_on:
      - timescaledb
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@timescaledb:5432/${DB_NAME}
    restart: unless-stopped
    networks:
      - data_analysis_net

  timescaledb:
    build:
      context: ./database
      args:
        - POSTGRES_PASSWORD=${DB_PASSWORD}
    container_name: da_timescaledb
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "6432:5432"
    volumes:
      - ./data/timescaledb:/var/lib/postgresql/data
      - ./database/schema:/app/database/schema
    restart: unless-stopped
    networks:
      - data_analysis_net

  grafana:
    image: grafana/grafana:latest
    container_name: da_grafana
    user: "${UID}:${GID}"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin123}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_HTTP_PORT=3000
      - GF_SERVER_PROTOCOL=http
      - GF_SERVER_DOMAIN=localhost
      - GF_SERVER_ROOT_URL=http://localhost:3000
    ports:
      - 6700:3000
    volumes:
      - ./data/grafana:/var/lib/grafana
    depends_on:
      - timescaledb
    restart: unless-stopped 
    networks:
      - data_analysis_net

volumes:
  app_home:
  conda_data:
  timescaledb_data:
  grafana_data: 

networks:
  data_analysis_net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"