version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_USER=${APP_USER:-developer}
        - APP_USER_PASSWORD=${APP_USER_PASSWORD:-developer123}
    container_name: da_monitor
    volumes:
      - .:/workspace
    depends_on:
      - timescaledb
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@timescaledb:5432/${DB_NAME}
    restart: unless-stopped
    networks:
      - data_analysis_net

  timescaledb:
    build:
      context: ./database
      args:
        - POSTGRES_PASSWORD=${DB_PASSWORD}
    container_name: da_timescaledb
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA=/var/lib/postgresql/17/main
    ports:
      - "6432:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/17
      - ./database/schema:/app/database/schema
    restart: unless-stopped
    networks:
      - data_analysis_net

  grafana:
    image: grafana/grafana:latest
    container_name: da_grafana
    user: "${UID}:${GID}"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin123}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_HTTP_PORT=3000
      - GF_SERVER_PROTOCOL=http
      - GF_SERVER_DOMAIN=localhost
      - GF_SERVER_ROOT_URL=http://localhost:3000
    ports:
      - 6700:3000
    volumes:
      - ./data/grafana:/var/lib/grafana
    depends_on:
      - timescaledb
    restart: unless-stopped 
    networks:
      - data_analysis_net

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: da_n8n
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=${DB_NAME}
      - DB_POSTGRESDB_HOST=timescaledb
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=${DB_USER}
      - DB_POSTGRESDB_SCHEMA=public
      - DB_POSTGRESDB_PASSWORD=${DB_PASSWORD}
      - N8N_HOST=0.0.0.0
      - N8N_PROTOCOL=http
      - N8N_SECURE_COOKIE=false
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY:-a-secure-encryption-key-for-n8n}
      - N8N_PERSONALIZATION_ENABLED=false
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - timescaledb
    restart: unless-stopped
    networks:
      - data_analysis_net

volumes:
  app_home:
    external: true
  conda_data:
    external: true
  timescaledb_data:
    external: true
  grafana_data:
    external: true
  n8n_data:
    external: true

networks:
  data_analysis_net:
    driver: bridge