version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_USER=${APP_USER:-developer}
        - APP_USER_PASSWORD=${APP_USER_PASSWORD:-developer123}
    container_name: gpu_monitor
    volumes:
      - .:/workspace
    depends_on:
      - timescaledb
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@timescaledb:5432/${DB_NAME}
    restart: unless-stopped
    networks:
      - data_analysis_net

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: gpu_timescaledb
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - data_analysis_net

  grafana:
    image: grafana/grafana:latest
    container_name: gpu_grafana
    user: "472"  # Grafana's default user
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin123}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_HTTP_PORT=3000
      - GF_SERVER_PROTOCOL=http
      - GF_SERVER_DOMAIN=localhost
      - GF_SERVER_ROOT_URL=http://localhost:3000
    ports:
      - 3000:3000
    volumes:
      - ./data/grafana:/var/lib/grafana
    depends_on:
      - timescaledb
    restart: unless-stopped 
    networks:
      - data_analysis_net

volumes:
  app_home:
  conda_data:
  timescaledb_data:
  grafana_data: 

networks:
  data_analysis_net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"