// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package analysis_db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Metric struct {
	ID        int32
	Name      string
	Value     float64
	Timestamp pgtype.Timestamptz
}
