// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package analysis_db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type EiaBulkElectricityDatum struct {
	ID          int32
	SeriesID    string
	Name        string
	Units       string
	Frequency   pgtype.Text
	Copyright   pgtype.Text
	Source      pgtype.Text
	Iso3166     pgtype.Text
	Location    interface{}
	Geography   pgtype.Text
	StartDate   pgtype.Timestamptz
	EndDate     pgtype.Timestamptz
	LastUpdated pgtype.Timestamptz
	Data        []byte
	CreatedAt   pgtype.Timestamptz
}

type EiaEntity struct {
	ID          int32
	ApiEntityID string
	Name        string
	Description pgtype.Text
	Metadata    []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type EiaGenerator struct {
	ID                         int32
	CompoundID                 string
	PlantID                    pgtype.Int4
	GeneratorCode              string
	Name                       pgtype.Text
	TechnologyDescription      pgtype.Text
	EnergySourceCode           pgtype.Text
	EnergySourceDescription    pgtype.Text
	PrimeMoverCode             pgtype.Text
	PrimeMoverDescription      pgtype.Text
	OperatingStatus            pgtype.Text
	NameplateCapacityMw        pgtype.Float8
	NetSummerCapacityMw        pgtype.Float8
	NetWinterCapacityMw        pgtype.Float8
	OperatingYearMonth         pgtype.Date
	PlannedDerateSummerCapMw   pgtype.Float8
	PlannedDerateYearMonth     pgtype.Date
	PlannedUprateSummerCapMw   pgtype.Float8
	PlannedUprateYearMonth     pgtype.Date
	PlannedRetirementYearMonth pgtype.Date
	Metadata                   []byte
	CreatedAt                  pgtype.Timestamptz
	UpdatedAt                  pgtype.Timestamptz
}

type EiaPlantCapacity struct {
	ID                         int32
	PlantID                    pgtype.Int4
	Timestamp                  pgtype.Timestamptz
	NameplateCapacityMw        pgtype.Float8
	NetSummerCapacityMw        pgtype.Float8
	NetWinterCapacityMw        pgtype.Float8
	PlannedDerateSummerCapMw   pgtype.Float8
	PlannedUprateSummerCapMw   pgtype.Float8
	OperatingYearMonth         pgtype.Date
	PlannedDerateYearMonth     pgtype.Date
	PlannedUprateYearMonth     pgtype.Date
	PlannedRetirementYearMonth pgtype.Date
	SourceTimestamp            pgtype.Timestamptz
	DataPeriod                 pgtype.Text
	Metadata                   []byte
	CreatedAt                  pgtype.Timestamptz
}

type EiaPlantGeneration struct {
	ID                       int32
	PlantID                  pgtype.Int4
	GeneratorID              pgtype.Int4
	Timestamp                pgtype.Timestamptz
	Period                   pgtype.Text
	Generation               pgtype.Float8
	GenerationUnits          pgtype.Text
	GrossGeneration          pgtype.Float8
	GrossGenerationUnits     pgtype.Text
	ConsumptionForEg         pgtype.Float8
	ConsumptionForEgUnits    pgtype.Text
	ConsumptionForEgBtu      pgtype.Float8
	ConsumptionForEgBtuUnits pgtype.Text
	TotalConsumption         pgtype.Float8
	TotalConsumptionUnits    pgtype.Text
	TotalConsumptionBtu      pgtype.Float8
	TotalConsumptionBtuUnits pgtype.Text
	AverageHeatContent       pgtype.Float8
	AverageHeatContentUnits  pgtype.Text
	SourceTimestamp          pgtype.Timestamptz
	Metadata                 []byte
	CreatedAt                pgtype.Timestamptz
}

type EiaPowerPlant struct {
	ID              int32
	ApiPlantID      string
	EntityID        pgtype.Int4
	Name            string
	County          pgtype.Text
	State           pgtype.Text
	Location        interface{}
	PlantCode       pgtype.Text
	FuelType        pgtype.Text
	PrimeMover      pgtype.Text
	OperatingStatus pgtype.Text
	Metadata        []byte
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type KmzFeature struct {
	ID          int32
	SourceID    string
	Name        pgtype.Text
	Description pgtype.Text
	Metadata    []byte
	Geometry    interface{}
	CreatedAt   pgtype.Timestamptz
}

type Metric struct {
	ID        int32
	Name      string
	Value     float64
	Timestamp pgtype.Timestamptz
}
