# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.28.0
import dataclasses
import datetime
from typing import Optional


@dataclasses.dataclass()
class Metric:
    id: int
    name: str
    value: float
    timestamp: Optional[datetime.datetime]
